### ISSUE TITLE
[dexter-vs] Missing dexter-result.xml

### ISSUE THREAD

**Issue by JanSawicki** [Samsung/Dexter#179] opened 2018-07-09 07:47 UTC
**What I did**
I followed the manual](https://dexter.atlassian.net/wiki/spaces/DW/pages/20742160/Dexter+Visual+Studio) and run the first analysis on a sample project [ConsoleApplication1.zip](https://github.com/Samsung/Dexter/files/2175035/ConsoleApplication1.zip).

**What happened**
![dextercscrcsvsplugin_dexter-result](https://user-images.githubusercontent.com/29917202/42437244-cced5be8-835c-11e8-9965-a8d5046c8c6f.gif)
I have encountered and error:
> Error: Unable to access jarfile C:\Program
> Error during analysis: Cannot find result file: *Path to dexter-cli* \dexter-cli\bin\dexter-result.xml

**My workaround**
A trial and error approach lead me to putting an **_empty_** file "_dexter-result.xml_" inside the "_dexter-cli\bin_" directory. The analysis was performed flawlessly. 

**My question**
I am not sure if that is the right solution (what is?) and overall if it is the excepted/desired behavior. Perhaps I missed some steps.

**Comment by JanSawicki** [comment] 2018-07-09 08:05
**Update**
Actually the problem concerned access rights to the _dexter-cli_ folder which can actually be seen on the screenshot I attached earlier "_Error: Unable to access jarfile C:\Program_" which I hastily ignored. 

**The solution**
I resolved the issue by simply putting the _dexter-cli_ directory somewhere else on the drive and pointing to it from the Dexter VS plugin.

**Comment by KarolAntczak** [comment] 2018-07-09 08:12
Hi, Jan!

Missing 'dexter-result.xml' was not the problem - it should be created after the analysis is finished. 
As you mentioned, the cause of the problem was permission issue - dexter was unable to create this file. 

Since it was not caused by the application, I am closing this issue.

**Closed by KarolAntczak** 2018-07-09 08:12 UTC
